version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://YashGoyal:gEXYZ1zLK8eMT22O@cluster0.wvsw0ye.mongodb.net/rationDB?retryWrites=true&w=majority

  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
